// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#ifndef _AQM_UI_UI_H
#define _AQM_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_fl_logo_png);    // assets/fl_logo.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png

// FONTS
LV_FONT_DECLARE(ui_font_newfont);
LV_FONT_DECLARE(ui_font_typeWriter18);
LV_FONT_DECLARE(ui_font_typeWriter22);
LV_FONT_DECLARE(ui_font_typeWriter22Bold);
LV_FONT_DECLARE(ui_font_typeWriter26Bold);
LV_FONT_DECLARE(ui_font_ramen);
LV_FONT_DECLARE(ui_font_roboto16);
LV_FONT_DECLARE(ui_font_roboto18);
LV_FONT_DECLARE(ui_font_roboto28Bold);
LV_FONT_DECLARE(ui_font_roboto32Regular);
LV_FONT_DECLARE(ui_font_roboto32Thin);
LV_FONT_DECLARE(ui_font_roboto34Thin);
LV_FONT_DECLARE(ui_font_roboto38Regular);
LV_FONT_DECLARE(ui_font_roboto40Thin);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
