// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#include "ui.h"

void PasswordtextPressed(lv_event_t * e)
{
	// Your code here
}

void UsertxtPressed(lv_event_t * e)
{
	// Your code here
}

void loginBtn(lv_event_t * e)
{
	// Your code here
}
