// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_siriusLabel2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_flLabel = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_OUT, 2000, 1000, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x9FF2EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x5EA2BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_siriusLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_siriusLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_siriusLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_siriusLabel2, -10);
    lv_obj_set_y(ui_siriusLabel2, -55);
    lv_obj_set_align(ui_siriusLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_siriusLabel2, "SIRIUS iCRMS ");
    lv_obj_set_style_text_color(ui_siriusLabel2, lv_color_hex(0x070000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_siriusLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_siriusLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_siriusLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_siriusLabel2, &ui_font_roboto40Thin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_fl_logo_png);
    lv_obj_set_width(ui_Image3, 39);
    lv_obj_set_height(ui_Image3, 36);
    lv_obj_set_x(ui_Image3, -11);
    lv_obj_set_y(ui_Image3, 74);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 500);
    lv_obj_set_style_bg_color(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Image3, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -14);
    lv_obj_set_y(ui_Label12, -14);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Air Quality Monitoring System ");

    ui_flLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_flLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_flLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_flLabel, -14);
    lv_obj_set_y(ui_flLabel, 121);
    lv_obj_set_align(ui_flLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_flLabel, "FountLab Solutions ");

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_siriusLabel2 = NULL;
    ui_Image3 = NULL;
    ui_Label12 = NULL;
    ui_flLabel = NULL;

}
