// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_passwordTextArea = NULL;
lv_obj_t * ui_usernameTextArea = NULL;
lv_obj_t * ui_loginButton2 = NULL;
lv_obj_t * ui_loginLabel = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_backLabelsettingScreen3 = NULL;
lv_obj_t * ui_timeLabel2 = NULL;
lv_obj_t * ui_dateLabel2 = NULL;
lv_obj_t * ui_siriusLabel3 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_checkLabel = NULL;
// event funtions
void ui_event_passwordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_passwordTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        PasswordtextPressed(e);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_usernameTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_usernameTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        UsertxtPressed(e);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_loginButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loginBtn(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_checkLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_checkLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x9FF2EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen3, lv_color_hex(0x5EA2BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 676);
    lv_obj_set_height(ui_Panel1, 340);
    lv_obj_set_x(ui_Panel1, 4);
    lv_obj_set_y(ui_Panel1, 14);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordTextArea = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_passwordTextArea, 217);
    lv_obj_set_height(ui_passwordTextArea, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_passwordTextArea, 168);
    lv_obj_set_y(ui_passwordTextArea, -76);
    lv_obj_set_align(ui_passwordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordTextArea, "Password");
    lv_textarea_set_one_line(ui_passwordTextArea, true);
    lv_textarea_set_password_mode(ui_passwordTextArea, true);
    lv_obj_set_style_bg_color(ui_passwordTextArea, lv_color_hex(0xD8FBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_passwordTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_passwordTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_passwordTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_passwordTextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usernameTextArea = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_usernameTextArea, 223);
    lv_obj_set_height(ui_usernameTextArea, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_usernameTextArea, -165);
    lv_obj_set_y(ui_usernameTextArea, -74);
    lv_obj_set_align(ui_usernameTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_usernameTextArea, "Username");
    lv_textarea_set_one_line(ui_usernameTextArea, true);
    lv_obj_set_style_bg_color(ui_usernameTextArea, lv_color_hex(0xD8FBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_usernameTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_usernameTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_usernameTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_usernameTextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginButton2 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_loginButton2, 100);
    lv_obj_set_height(ui_loginButton2, 50);
    lv_obj_set_x(ui_loginButton2, -1);
    lv_obj_set_y(ui_loginButton2, 134);
    lv_obj_set_align(ui_loginButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_loginButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loginButton2, lv_color_hex(0xF41F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loginButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginLabel = lv_label_create(ui_loginButton2);
    lv_obj_set_width(ui_loginLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loginLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loginLabel, -3);
    lv_obj_set_y(ui_loginLabel, 0);
    lv_obj_set_align(ui_loginLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loginLabel, "LOGIN");
    lv_obj_set_style_text_color(ui_loginLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loginLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image1, &ui_img_fl_logo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_Image1, 2);
    lv_obj_set_y(ui_Image1, -116);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 500);

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -357);
    lv_obj_set_y(ui_Button2, 227);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x5EA2BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Button2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backLabelsettingScreen3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_backLabelsettingScreen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabelsettingScreen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backLabelsettingScreen3, -1);
    lv_obj_set_y(ui_backLabelsettingScreen3, -1);
    lv_obj_set_align(ui_backLabelsettingScreen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backLabelsettingScreen3, "Back");
    lv_obj_set_style_text_color(ui_backLabelsettingScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backLabelsettingScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_timeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLabel2, -351);
    lv_obj_set_y(ui_timeLabel2, -224);
    lv_obj_set_align(ui_timeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel2, "TIME");
    lv_obj_set_style_text_font(ui_timeLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLabel2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_dateLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLabel2, 348);
    lv_obj_set_y(ui_dateLabel2, -224);
    lv_obj_set_align(ui_dateLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLabel2, "DATE");
    lv_obj_set_style_text_font(ui_dateLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_siriusLabel3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_siriusLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_siriusLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_siriusLabel3, -4);
    lv_obj_set_y(ui_siriusLabel3, -207);
    lv_obj_set_align(ui_siriusLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_siriusLabel3, "SIRIUS iCRMS ");
    lv_obj_set_style_text_color(ui_siriusLabel3, lv_color_hex(0x070000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_siriusLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_siriusLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_siriusLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_siriusLabel3, &ui_font_roboto32Thin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard1, 350);
    lv_obj_set_height(ui_Keyboard1, 143);
    lv_obj_set_x(ui_Keyboard1, 3);
    lv_obj_set_y(ui_Keyboard1, 41);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_checkLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_checkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_checkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_checkLabel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checkLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_passwordTextArea, ui_event_passwordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_usernameTextArea, ui_event_usernameTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loginButton2, ui_event_loginButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel1 = NULL;
    ui_passwordTextArea = NULL;
    ui_usernameTextArea = NULL;
    ui_loginButton2 = NULL;
    ui_loginLabel = NULL;
    ui_Image1 = NULL;
    ui_Button2 = NULL;
    ui_backLabelsettingScreen3 = NULL;
    ui_timeLabel2 = NULL;
    ui_dateLabel2 = NULL;
    ui_siriusLabel3 = NULL;
    ui_Keyboard1 = NULL;
    ui_checkLabel = NULL;

}
