// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_vocPanel;
extern lv_obj_t * ui_humidityPanel;
extern lv_obj_t * ui_co2Panel;
extern lv_obj_t * ui_tempPanel;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_dateLabel;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_humidityLabel;
extern lv_obj_t * ui_vocLabel;
extern lv_obj_t * ui_co2Label;
extern lv_obj_t * ui_tempValueLabel;
extern lv_obj_t * ui_humidityValueLabel;
extern lv_obj_t * ui_vocValueLabel;
extern lv_obj_t * ui_co2ValueLabel;
extern lv_obj_t * ui_siriusLabel4;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_settingsButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

