// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_vocPanel = NULL;
lv_obj_t * ui_humidityPanel = NULL;
lv_obj_t * ui_co2Panel = NULL;
lv_obj_t * ui_tempPanel = NULL;
lv_obj_t * ui_timeLabel = NULL;
lv_obj_t * ui_dateLabel = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_humidityLabel = NULL;
lv_obj_t * ui_vocLabel = NULL;
lv_obj_t * ui_co2Label = NULL;
lv_obj_t * ui_tempValueLabel = NULL;
lv_obj_t * ui_humidityValueLabel = NULL;
lv_obj_t * ui_vocValueLabel = NULL;
lv_obj_t * ui_co2ValueLabel = NULL;
lv_obj_t * ui_siriusLabel4 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_settingsButton = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x9FF2EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0x5EA2BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_vocPanel, 312);
    lv_obj_set_height(ui_vocPanel, 169);
    lv_obj_set_x(ui_vocPanel, 193);
    lv_obj_set_y(ui_vocPanel, 120);
    lv_obj_set_align(ui_vocPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_vocPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_vocPanel, lv_color_hex(0xC1F0F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vocPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_vocPanel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_humidityPanel, 315);
    lv_obj_set_height(ui_humidityPanel, 173);
    lv_obj_set_x(ui_humidityPanel, -203);
    lv_obj_set_y(ui_humidityPanel, 124);
    lv_obj_set_align(ui_humidityPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humidityPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_humidityPanel, lv_color_hex(0xC1F0F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humidityPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2Panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_co2Panel, 310);
    lv_obj_set_height(ui_co2Panel, 174);
    lv_obj_set_x(ui_co2Panel, 195);
    lv_obj_set_y(ui_co2Panel, -84);
    lv_obj_set_align(ui_co2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_co2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_co2Panel, lv_color_hex(0xC1F0F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_co2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_tempPanel, 310);
    lv_obj_set_height(ui_tempPanel, 175);
    lv_obj_set_x(ui_tempPanel, -205);
    lv_obj_set_y(ui_tempPanel, -82);
    lv_obj_set_align(ui_tempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempPanel, lv_color_hex(0xC1F0F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLabel, -351);
    lv_obj_set_y(ui_timeLabel, -224);
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "TIME");
    lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_dateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLabel, 346);
    lv_obj_set_y(ui_dateLabel, -224);
    lv_obj_set_align(ui_dateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLabel, "DATE");
    lv_obj_set_style_text_font(ui_dateLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, 202);
    lv_obj_set_height(ui_Label2, 29);
    lv_obj_set_x(ui_Label2, -201);
    lv_obj_set_y(ui_Label2, -140);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "TEMPERATURE");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_humidityLabel, 139);
    lv_obj_set_height(ui_humidityLabel, 29);
    lv_obj_set_x(ui_humidityLabel, -216);
    lv_obj_set_y(ui_humidityLabel, 60);
    lv_obj_set_align(ui_humidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidityLabel, "HUMIDITY");
    lv_obj_set_style_text_font(ui_humidityLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_vocLabel, 159);
    lv_obj_set_height(ui_vocLabel, 29);
    lv_obj_set_x(ui_vocLabel, 190);
    lv_obj_set_y(ui_vocLabel, -140);
    lv_obj_set_align(ui_vocLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocLabel, "VOC INDEX ");
    lv_obj_set_style_text_font(ui_vocLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2Label = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_co2Label, 64);
    lv_obj_set_height(ui_co2Label, 29);
    lv_obj_set_x(ui_co2Label, 180);
    lv_obj_set_y(ui_co2Label, 62);
    lv_obj_set_align(ui_co2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2Label, "CO2");
    lv_obj_set_style_text_font(ui_co2Label, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValueLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tempValueLabel, 86);
    lv_obj_set_height(ui_tempValueLabel, 29);
    lv_obj_set_x(ui_tempValueLabel, -212);
    lv_obj_set_y(ui_tempValueLabel, -54);
    lv_obj_set_align(ui_tempValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempValueLabel, "NC");
    lv_obj_set_style_text_font(ui_tempValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityValueLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_humidityValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidityValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidityValueLabel, -206);
    lv_obj_set_y(ui_humidityValueLabel, 138);
    lv_obj_set_align(ui_humidityValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidityValueLabel, "NC");
    lv_obj_set_style_text_font(ui_humidityValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vocValueLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_vocValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vocValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vocValueLabel, 201);
    lv_obj_set_y(ui_vocValueLabel, -63);
    lv_obj_set_align(ui_vocValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vocValueLabel, "NC");
    lv_obj_set_style_text_font(ui_vocValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ValueLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_co2ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_co2ValueLabel, 181);
    lv_obj_set_y(ui_co2ValueLabel, 141);
    lv_obj_set_align(ui_co2ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2ValueLabel, "NC");
    lv_obj_set_style_text_font(ui_co2ValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_siriusLabel4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_siriusLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_siriusLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_siriusLabel4, 17);
    lv_obj_set_y(ui_siriusLabel4, -207);
    lv_obj_set_align(ui_siriusLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_siriusLabel4, "SIRIUS iCRMS ");
    lv_obj_set_style_text_color(ui_siriusLabel4, lv_color_hex(0x070000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_siriusLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_siriusLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_siriusLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_siriusLabel4, &ui_font_roboto32Thin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 383);
    lv_obj_set_y(ui_Button3, 226);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x70B3CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButton = lv_img_create(ui_Button3);
    lv_img_set_src(ui_settingsButton, &ui_img_settings_png);
    lv_obj_set_width(ui_settingsButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsButton, -4);
    lv_obj_set_y(ui_settingsButton, -6);
    lv_obj_set_align(ui_settingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButton, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_settingsButton, 80);
    lv_obj_set_style_bg_color(ui_settingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_settingsButton, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_vocPanel = NULL;
    ui_humidityPanel = NULL;
    ui_co2Panel = NULL;
    ui_tempPanel = NULL;
    ui_timeLabel = NULL;
    ui_dateLabel = NULL;
    ui_Label2 = NULL;
    ui_humidityLabel = NULL;
    ui_vocLabel = NULL;
    ui_co2Label = NULL;
    ui_tempValueLabel = NULL;
    ui_humidityValueLabel = NULL;
    ui_vocValueLabel = NULL;
    ui_co2ValueLabel = NULL;
    ui_siriusLabel4 = NULL;
    ui_Button3 = NULL;
    ui_settingsButton = NULL;

}
