// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: AQM-ui

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel1;
extern void ui_event_passwordTextArea(lv_event_t * e);
extern lv_obj_t * ui_passwordTextArea;
extern void ui_event_usernameTextArea(lv_event_t * e);
extern lv_obj_t * ui_usernameTextArea;
extern void ui_event_loginButton2(lv_event_t * e);
extern lv_obj_t * ui_loginButton2;
extern lv_obj_t * ui_loginLabel;
extern lv_obj_t * ui_Image1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_backLabelsettingScreen3;
extern lv_obj_t * ui_timeLabel2;
extern lv_obj_t * ui_dateLabel2;
extern lv_obj_t * ui_siriusLabel3;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_checkLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

